---- 1)
SELECT e1.FIRST_NAME, e1.LAST_NAME
FROM EMPLOYEES e1
JOIN EMPLOYEES e2 ON e1.EMPLOYEE_ID = e2.MANAGER_ID
GROUP BY e1.FIRST_NAME, e1.LAST_NAME
HAVING COUNT(e1.MANAGER_ID) > 6

---- 2)
SELECT d.DEPARTMENT_NAME
    ,MIN(e.SALARY * (1 - e.COMISSION_PCT / 100)) AS min_salary
    ,MAX(e.SALARY * (1 - e.COMISSION_PCT / 100)) AS max_salary
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME

---- 3)
SELECT TOP 1 r.REGION_NAME, COUNT(1) AS cnt
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
JOIN COUNTRYES c ON l.COUNTRY_ID = c.COUNTRY_ID
JOIN REGIONS r ON c.REGION_ID = r.REGION_ID
GROUP BY r.REGION_NAME
ORDER BY cnt DESC

---- 4)
SELECT d.DEPARTMENT_NAME
	,(AVG(e.SALARY) / (SELECT AVG(SALARY) FROM  EMPLOYEES) - 1) * 100 AS CNT
FROM  EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME;

---- 5)
WITH job AS (SELECT j.EMPLOYEE_ID
			,j.DEPARTMENT_ID
			,CASE WHEN j.END_DATE IS NULL THEN DATEDIFF(YEAR, j.START_DATE, GETDATE())
			ELSE DATEDIFF(YEAR, j.START_DATE, j.END_DATE)
			END AS years
			FROM JOB_HISTORY j
			GROUP BY j.EMPLOYEE_ID, j.DEPARTMENT_ID)
SELECT e.FIRST_NAME
    	,e.LAST_NAME
	,job.years
FROM EMPLOYEES e
JOIN job ON e.EMPLOYEE_ID = job.EMPLOYEE_ID
WHERE job.years > 10

---- 6
SELECT FIRST_NAME
    ,LAST_NAME
    ,SALARY
FROM (SELECT EMPLOYEE_ID
	,FIRST_NAME
	,LAST_NAME
	,SALARY
        ,ROW_NUMBER() OVER (ORDER BY salary DESC) AS x
    	FROM EMPLOYEES)
WHERE x BETWEEN 5 AND 10;